services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - dummy
      - receipt
    env_file:
      - .env # This injects the variables into your Python container

  dummy:
    build:
      context: ./dummy
    ports:
      - "9000:9000"
    env_file:
      - .env
    environment:
      OTEL_SERVICE_NAME: dummy

  receipt:
    build:
      context: ./receipts
    ports:
      - "3001:3000"
    env_file:
      - .env
    environment:
      OTEL_SERVICE_NAME: receipt

volumes:
  postgres_data: